/* Inglés del visor: el HTML de viewer/index.html y los textos de las partes
   10 a 50. Al final se traduce la página, antes de que el motor tome sus
   elementos. */
I18N.add({
  // barra de herramientas
  'Frame anterior': 'Previous frame',
  'Frame siguiente': 'Next frame',
  'Herramientas de comparación': 'Comparison tools',
  'Diferencia amplificada por canal (D)': 'Per-channel amplified difference (D)',
  'Curva solar: revela banding y degradados (L)': 'Solar curve: reveals banding and gradients (L)',
  'Intensidad': 'Gain',
  'Resaltar diferencias en rojo (H)': 'Highlight differences in red (H)',
  'Calor': 'Heat',
  'Parpadeo izquierda/derecha (B)': 'Blink left/right (B)',
  'Parpadeo': 'Blink',
  'Ciego': 'Blind',
  'Elige un punto e inspecciona recortes 1:1 de todas las variantes (C)': 'Pick a point and inspect 1:1 crops of every variant (C)',
  'Recortes': 'Crops',
  '1:1 real en píxeles del dispositivo (O)': 'True 1:1 in device pixels (O)',
  'Escala con píxeles nítidos al hacer zoom (N)': 'Scale with sharp pixels when zooming (N)',
  'Nítido': 'Sharp',
  'Reiniciar zoom (F)': 'Reset zoom (F)',
  'Ajustar': 'Fit',
  'Compartir: link, BBCode para foros, Markdown y HTML': 'Share: link, BBCode for forums, Markdown and HTML',
  'Compartir': 'Share',
  'Atajos y controles (?)': 'Shortcuts and controls (?)',
  'Ayuda y atajos': 'Help and shortcuts',
  'Reportar esta página': 'Report this page',
  'Reportar': 'Report',
  'Izquierda': 'Left',
  'Derecha': 'Right',
  'Desplazar la lista': 'Scroll the list',
  'Variante izquierda': 'Left variant',
  'Variante derecha': 'Right variant',
  'Comando del encoder': 'Encoder command',
  'Ver el comando de la variante izquierda': 'Show the left variant\'s command',
  'Ver el comando de la variante derecha': 'Show the right variant\'s command',
  'Intercambiar izquierda y derecha (S)': 'Swap left and right (S)',
  // la comparación
  'Esta variante no tiene este cuadro': 'This variant does not have this frame',
  'ajustar': 'fit',
  'PARPADEO A/B': 'BLINK A/B',
  'haz clic en un punto (o muévelo con las flechas) para ver recortes 1:1': 'click a point (or move it with the arrow keys) to see 1:1 crops',
  'Recortes 1:1': '1:1 crops',
  'cerrar (Esc)': 'close (Esc)',
  // pie: atajos
  '←→ frame': '<kbd>←</kbd><kbd>→</kbd> frame',
  '1–9 variante (Shift = izquierda)': '<kbd>1</kbd>–<kbd>9</kbd> variant (<kbd>Shift</kbd> = left)',
  'S intercambiar': '<kbd>S</kbd> swap',
  'D diff': '<kbd>D</kbd> diff',
  'B parpadeo': '<kbd>B</kbd> blink',
  'C recortes': '<kbd>C</kbd> crops',
  'F ajustar': '<kbd>F</kbd> fit',
  '+/- ganancia': '<kbd>+</kbd>/<kbd>-</kbd> gain',
  'H calor': '<kbd>H</kbd> heat',
  'Espacio siguiente variante': '<kbd>Space</kbd> next variant',
  'N nítido': '<kbd>N</kbd> sharp',
  'L solar': '<kbd>L</kbd> solar',
  ',/. divisor': '<kbd>,</kbd>/<kbd>.</kbd> divider',
  'zoom con rueda/pellizco · arrastra para mover · doble clic ajusta': 'wheel or pinch to zoom · drag to move · double click to fit',
  // ayuda
  'Atajos y controles': 'Shortcuts and controls',
  'Cerrar (Esc)': 'Close (Esc)',
  'Frame anterior o siguiente.': 'Previous or next frame.',
  'Espacio': 'Space',
  'Siguiente variante a la derecha.': 'Next variant on the right.',
  '1 a 9': '<kbd>1</kbd> to <kbd>9</kbd>',
  'Elegir variante a la derecha. Con Shift, a la izquierda.': 'Pick the variant on the right. With Shift, on the left.',
  'Intercambiar izquierda y derecha.': 'Swap left and right.',
  'Activar o desactivar la diferencia amplificada.': 'Turn the amplified difference on or off.',
  'Aumentar o reducir la intensidad del diff.': 'Raise or lower the diff gain.',
  'Activar o desactivar el mapa de calor del diff.': 'Turn the diff heat map on or off.',
  'Activar o desactivar el parpadeo A/B.': 'Turn A/B blink on or off.',
  'Activar o desactivar la curva solar.': 'Turn the solar curve on or off.',
  'Elegir un punto para ver recortes 1:1. Con el modo activo, las flechas siembran y mueven el punto; con Shift, en pasos de 10 px.': 'Pick a point to see 1:1 crops. While the mode is on, the arrow keys place and move the point; with Shift, in 10 px steps.',
  'Ver un píxel de imagen por píxel del dispositivo.': 'Show one image pixel per device pixel.',
  'Ajustar la imagen al área disponible.': 'Fit the image to the available area.',
  'Alternar escala suave y píxeles nítidos.': 'Switch between smooth scaling and sharp pixels.',
  'Mover el divisor. Con Shift, moverlo en pasos mayores.': 'Move the divider. With Shift, in larger steps.',
  'Abrir esta ayuda.': 'Open this help.',
  'Cerrar ayuda, Compartir, comandos o recortes.': 'Close help, Share, commands or crops.',
  'Rueda o pellizco: zoom. Arrastra la imagen ampliada para moverla. Doble clic: ajustar. Mantén el cursor sobre una variante para consultar su comando, si tiene uno.': 'Wheel or pinch: zoom. Drag the zoomed image to move it. Double click: fit. Hover over a variant to see its command, if it has one.',
  'Teléfono: desliza para cambiar de frame, pellizca para acercar, cmd muestra el comando.': 'Phone: swipe to change frame, pinch to zoom, <b>cmd</b> shows the command.',
  'Los atajos no cambian la comparación mientras escribes en un campo.': 'Shortcuts do not change the comparison while you type in a field.',
  // reportar
  'Reportar página': 'Report page',
  'Contenido inapropiado': 'Inappropriate content',
  'Material ajeno / derechos': 'Someone else\'s material / copyright',
  'Spam o engaño': 'Spam or scam',
  'Otro': 'Other',
  'detalle (opcional)': 'details (optional)',
  'Enviar reporte': 'Send report',
  'Cerrar': 'Close',
  'Enviando…': 'Sending…',
  'Reporte enviado. Gracias.': 'Report sent. Thank you.',
  'No se pudo enviar: {}': 'Could not send: {}',
  // compartir
  'Compartir comparación': 'Share comparison',
  'Guarda la comparación visible como PNG sin pérdida. El enlace conserva el frame, las variantes y los ajustes.': 'Saves the visible comparison as a lossless PNG. The link keeps the frame, the variants and the settings.',
  'La imagen conserva el modo ciego. El enlace abre la comparación sin la asignación privada de esta sesión.': 'The image keeps blind mode. The link opens the comparison without this session\'s private assignment.',
  'vista a compartir': 'view to share',
  'Llave de borrado del autor': 'Author\'s delete key',
  'La recibiste al publicar': 'You received it when you published',
  'usar la llave guardada (esta sesión)': 'use the saved key (this session)',
  'Solo el autor puede reemplazar la imagen compartida. La nueva imagen aparecerá también en los enlaces que ya publicaste.': 'Only the author can replace the shared image. The new image will also show in the links you already posted.',
  'Descargar PNG': 'Download PNG',
  'sube esta imagen exacta a gatos.pics y arma el BBCode para foros': 'uploads this exact image to gatos.pics and builds the BBCode for forums',
  'Subir y obtener BBCode': 'Upload and get BBCode',
  'Progreso del envío de la imagen': 'Image upload progress',
  'Cancelar envío': 'Cancel upload',
  'Reintentar esta imagen': 'Retry this image',
  'Borrar esta página…': 'Delete this page…',
  'Enlace a esta vista': 'Link to this view',
  'copiado ✓': 'copied ✓',
  'seleccionado: Ctrl+C': 'selected: Ctrl+C',
  'No se pudo generar el PNG.': 'Could not create the PNG.',
  'pega la llave de borrado para poder eliminar la página': 'paste the delete key to remove the page',
  '¿Borrar esta página y su imagen compartida? No se puede deshacer.': 'Delete this page and its shared image? This cannot be undone.',
  'Borrando…': 'Deleting…',
  'Página borrada.': 'Page deleted.',
  'No se pudo borrar: {}': 'Could not delete: {}',
  'La imagen pudo actualizarse. Reintentar reemplaza la misma URL.': 'The image may have been updated. Retrying replaces the same URL.',
  'BBCode (foros, la vista exacta clicable)': 'BBCode (forums, the exact view, clickable)',
  'Imagen directa': 'Direct image',
  'Ingresa la llave que recibiste al publicar.': 'Enter the key you received when you published.',
  'No se puede compartir: una imagen no cargó.': 'Cannot share: an image did not load.',
  'Espera a que terminen de cargar las dos imágenes.': 'Wait for both images to finish loading.',
  'No se puede compartir el diff: revisa las dimensiones de las imágenes.': 'Cannot share the diff: check the image dimensions.',
  // prueba ciega
  'Prueba ciega': 'Blind test',
  'Prueba ciega: compara todas las versiones de a pares sin saber cuál es cuál, y mira cuál gana (G)': 'Blind test: compare every version in pairs without knowing which is which, and see which one wins (G)',
  'G prueba ciega': '<kbd>G</kbd> blind test',
  'Abrir la prueba ciega: todas las versiones de a pares, sin saber cuál es cuál.': 'Open the blind test: every version in pairs, without knowing which is which.',
  'Se ve mejor la de la izquierda (←)': 'The left one looks better (←)',
  'Se ve mejor la de la derecha (→)': 'The right one looks better (→)',
  'No veo diferencia (↑)': 'I see no difference (↑)',
  'Empate': 'Tie',
  'Volver a la comparación anterior (Retroceso)': 'Go back to the previous comparison (Backspace)',
  'Atrás': 'Back',
  'Salir de la prueba': 'Leave the test',
  'Variante {}': 'Variant {}',
  'Vas a ordenar las {} versiones de mejor a peor sin saber cuál es cuál. Cada una recibe un número al azar y lo conserva toda la prueba.': 'You will rank the {} versions from best to worst without knowing which is which. Each one gets a random number and keeps it for the whole test.',
  'En cada una eliges la que se ve mejor, o empate. Puedes usar zoom, diff y parpadeo.': 'In each one you pick the one that looks better, or a tie. You can use zoom, diff and blink.',
  'Comparación {} · como mucho {} · ¿cuál se ve mejor?': 'Comparison {} · {} at most · which looks better?',
  'comparaciones ganadas, empatadas y perdidas': 'comparisons won, tied and lost',
  'Respondiste {} comparaciones. Los pares que no viste se ordenaron con tus respuestas: si una le gana a otra y esa a una tercera, la primera va antes.': 'You answered {} comparisons. The pairs you did not see were ordered from your answers: if one beats another and that one beats a third, the first goes ahead.',
  'Ordenada por el puesto medio en que quedó cada versión: cuanto más bajo, mejor.': 'Sorted by the average place each version finished in: the lower, the better.',
  'Puesto medio': 'Average place',
  'Son como mucho {} comparaciones.': 'It takes {} comparisons at most.',
  'Son como mucho {} comparaciones, y suelen ser bastantes menos: la prueba elige cada una según lo que vas respondiendo y se detiene cuando el orden queda claro.': 'It takes {} comparisons at most, and usually far fewer: the test picks each one from your answers so far and stops when the order is settled.',
  'Empezar': 'Start',
  'Ver la tabla de todos': 'See everyone\'s standings',
  'Cancelar': 'Cancel',
  'Ver la tabla antes de hacer la prueba condiciona tu juicio.': 'Seeing the standings before taking the test will bias your judgment.',
  '¿Salir de la prueba? Se pierde lo que llevas.': 'Leave the test? Your answers so far will be lost.',
  'Tu resultado': 'Your result',
  'Puesto': 'Place',
  'Era': 'Was',
  'Versión': 'Version',
  'G-E-P': 'W-T-L',
  'Ya enviaste un resultado de esta página desde este navegador: esta prueba no se suma otra vez.': 'You already sent a result for this page from this browser: this test will not be added again.',
  'Al terminar, tu resultado se suma a la tabla de todos. No se guarda nada sobre ti.': 'When you finish, your result is added to everyone\'s standings. Nothing about you is stored.',
  'Esta copia no está publicada en gatos.pics: el resultado no se envía.': 'This copy is not published on gatos.pics: the result is not sent.',
  'Ya habías enviado un resultado de esta página desde este navegador: este no se sumó.': 'You had already sent a result for this page from this browser: this one was not added.',
  'Sumando tu resultado a la tabla de todos…': 'Adding your result to everyone\'s standings…',
  'Tu resultado se sumó a la tabla de todos. No se guardó nada sobre ti.': 'Your result was added to everyone\'s standings. Nothing about you was stored.',
  'No se pudo enviar tu resultado: {}': 'Could not send your result: {}',
  'Reintentar el envío': 'Retry sending',
  'Repetir la prueba': 'Take the test again',
  'Tabla de todos': 'Everyone\'s standings',
  '1 prueba enviada.': '1 test sent.',
  '{} pruebas enviadas.': '{} tests sent.',
  'Puestos en cada prueba': 'Placings in each test',
  'Volver a mi resultado': 'Back to my result',
  'Hacer la prueba': 'Take the test',
  'No se pudo leer la tabla: {}': 'Could not read the standings: {}',
  // estado y modos
  'Comparación': 'Comparison',
  'Comparación a ciegas': 'Blind comparison',
  'manifest inválido: JSON truncado o malformado': 'invalid manifest: truncated or malformed JSON',
  'manifest inválido: faltan frames o hay menos de 2 variantes': 'invalid manifest: frames are missing or there are fewer than 2 variants',
  'no se encontraron datos de comparación (sin paquete embebido, sin manifest.json)': 'no comparison data found (no embedded package, no manifest.json)',
  'la imagen no cargó': 'the image did not load',
  'la imagen derecha no cargó': 'the right image did not load',
  'cargando…': 'loading…',
  'Diff no disponible: una variante no tiene este cuadro.': 'Diff unavailable: a variant does not have this frame.',
  'Diff no disponible: una imagen no cargó.': 'Diff unavailable: an image did not load.',
  'Diff no disponible: las imágenes tienen dimensiones distintas.': 'Diff unavailable: the images have different dimensions.',
  'Diff: cargando…': 'Diff: loading…',
  ' · calor (Δ≥{} en rojo)': ' · heat (Δ≥{} in red)',
  ' · calor': ' · heat',
  'Diff ×{}{} · color = canal que difiere · Δ media {}/255': 'Diff ×{}{} · color = channel that differs · mean Δ {}/255',
  'Diff ×{}{} · Δ media {}/255': 'Diff ×{}{} · mean Δ {}/255',
  'Diff ×{} · calculando…': 'Diff ×{} · computing…',
  'Parpadeo A/B': 'Blink A/B',
  'sin este cuadro': 'no such frame',
  'S2 media {}': 'S2 mean {}',
  'Recortes 1:1 @ {},{} (px nativos)': '1:1 crops @ {},{} (native px)',
  'izq.': 'left',
  'der.': 'right',
  ' y ': ' and ',
  ' · sin este cuadro: {}': ' · missing this frame: {}',
  'Frame {} · izquierda: {} · derecha: {} · CIEGO{}': 'Frame {} · left: {} · right: {} · BLIND{}',
  'Inicio del clip {} · ': 'Clip start {} · ',
  'CIEGO': 'BLIND',
  '{}Frame {} (#{}{}) · izq. {} · der. {}{}{}': '{}Frame {} (#{}{}) · left {} · right {}{}{}',
  'en ámbar lo que difiere de <b>{}</b>': 'in amber, what differs from <b>{}</b>',
  'comando': 'command',
  'Copiar': 'Copy',
  'Copiado ✓': 'Copied ✓',
  'Falló la copia': 'Copy failed',
});
I18N.apply();
I18N.wire();
