/* Inglés del creador: el HTML de app/index.html y los textos de builder.js,
   capture.js, publish.js, guide.js y zip.js. Cómo se agrega un texto: ver
   viewer/src/05-i18n.js. Al final se traduce la página, antes de que
   builder.js tome sus elementos. */
I18N.add({
  // bienvenida
  'Compara dos capturas y comparte el resultado.': 'Compare two screenshots and share the result.',
  '1 · Agrega dos imágenes': '1 · Add two images',
  'Elige capturas del mismo momento. Una va a la izquierda y otra a la derecha.': 'Pick screenshots of the same moment. One goes on the left, the other on the right.',
  '2 · Revisa la comparación': '2 · Check the comparison',
  'Abre la vista previa. Mueve el divisor o amplía un detalle.': 'Open the preview. Move the divider or zoom into a detail.',
  '3 · Guarda o publica': '3 · Save or publish',
  'Descarga un archivo para abrirlo sin internet, o publica para obtener un enlace.': 'Download a file that opens offline, or publish to get a link.',
  'Tus imágenes se quedan en este navegador hasta que eliges Publicar.': 'Your images stay in this browser until you choose Publish.',
  'Crear comparación': 'Create a comparison',
  'Ver un ejemplo': 'See an example',
  'Abre el ejemplo como proyecto para editarlo': 'Opens the example as a project you can edit',
  'Editar el ejemplo': 'Edit the example',
  'Guías paso a paso sobre la pantalla': 'Step-by-step guides on the screen',
  'Guíame paso a paso': 'Guide me step by step',
  'no mostrar de nuevo': 'do not show again',
  'Generando ejemplo…': 'Building the example…',
  'Cargar el ejemplo descarta tu proyecto actual. ¿Continuar?': 'Loading the example discards your current project. Continue?',
  'ejemplo sintético · nada real': 'synthetic example · nothing real',
  'gatos.pics · ejemplo': 'gatos.pics · example',
  'ejemplo {}': 'example {}',
  'Fuente': 'Source',
  'referencia': 'reference',
  'desenfoque + ruido simulados': 'simulated blur + noise',
  'encoder --entrada in.png --crf 26 --preset 4 --salida out.png': 'encoder --input in.png --crf 26 --preset 4 --output out.png',
  // barra superior
  'creador': 'creator',
  'Básico': 'Basic',
  'Avanzado': 'Advanced',
  'Abrir un proyecto .cmp (también puedes soltarlo en cualquier parte)': 'Open a .cmp project (you can also drop it anywhere)',
  'Abrir': 'Open',
  'Subir las imágenes y los datos de esta comparación a gatos.pics': 'Upload this comparison\'s images and data to gatos.pics',
  'Publicar': 'Publish',
  'Reemplazar el contenido de una página ya publicada con este proyecto, sin cambiar su enlace': 'Replace the content of a page you already published with this project, keeping its link',
  'Actualizar página': 'Update page',
  'Guardar el proyecto como .cmp (Ctrl+S)': 'Save the project as .cmp (Ctrl+S)',
  'Guardar': 'Save',
  'Ayuda': 'Help',
  'Vista previa': 'Preview',
  'Progreso de la publicación': 'Publishing progress',
  'Cancelar envío': 'Cancel upload',
  'Reintentar el mismo paquete': 'Retry the same package',
  // Básico
  'Compara imágenes': 'Compare images',
  'Suelta todas las capturas de una vez. Si los nombres dicen la versión y el cuadro, se agrupan solas: cada cuadro con todas sus versiones. Si no, llena cada versión por separado: «Elegir sus imágenes» (o suéltalas sobre su nombre) las pone en fila, en orden de nombre. Datos por versión (códec, comando, métricas): usa Avanzado.':
    'Drop all your screenshots at once. If the file names say the version and the frame, they group themselves: each frame with all its versions. If not, fill each version separately: "Choose its images" (or drop them on its name) lines them up in name order. For per-version data (codec, command, metrics), use Advanced.',
  'Elegir imágenes': 'Choose images',
  'Suelta imágenes aquí': 'Drop images here',
  'o haz clic para elegir archivos. PNG, WebP o JPEG.': 'or click to choose files. PNG, WebP or JPEG.',
  'nombres como fuente_01, Encode - 01 o 01_encode se agrupan por cuadro, con 2, 3 o más versiones: la referencia (fuente, src, máster) queda a la izquierda.':
    'names like <span class="mono">source_01</span>, <span class="mono">Encode - 01</span> or <span class="mono">01_encode</span> are grouped by frame, with 2, 3 or more versions: the reference (source, src, master) goes on the left.',
  'Ningún nombre parece la referencia (fuente, src, máster): la columna izquierda es una suposición. Revísala.': 'No name looks like the reference (source, src, master): the left column is a guess. Check it.',
  '1 cuadro no tiene todas las versiones: completa los huecos o quita la fila.': '1 frame is missing a version: fill the gaps or remove the row.',
  '{} cuadros no tienen todas las versiones: completa los huecos o quita la fila.': '{} frames are missing a version: fill the gaps or remove the row.',
  '{} y {} parecen la misma variante: se completó el par por orden. Revísalo.': '{} and {} look like the same variant: the pair was completed in order. Check it.',
  '{} y {} parecen la misma variante: se emparejaron por orden. Revísalos.': '{} and {} look like the same variant: they were paired in order. Check them.',
  'Una página admite hasta 12 versiones y aquí hay {}: quita {} con la × junto a su nombre.': 'A page takes up to 12 versions and there are {} here: remove {} with the × next to its name.',
  'Una página admite hasta 200 cuadros y aquí hay {}: quita {}.': 'A page takes up to 200 frames and there are {} here: remove {}.',
  'par': 'pair',
  'cuadro': 'frame',
  'versiones': 'versions',
  'versión': 'version',
  'Nombre de la versión {}': 'Name of version {}',
  'Elegir sus imágenes': 'Choose its images',
  'Elige (o suelta aquí) todas las imágenes de esta versión: llenan su columna en orden de nombre': 'Choose (or drop here) all the images of this version: they fill its column in name order',
  'Elegir todas las imágenes de la versión {}': 'Choose all the images of version {}',
  'Quitar esta versión': 'Remove this version',
  'Quitar la versión {}': 'Remove version {}',
  '¿Quitar la versión «{}» y sus imágenes?': 'Remove version "{}" and its images?',
  '+ versión': '+ version',
  'Agregar otra versión a cada cuadro': 'Add another version to every frame',
  'Derecha': 'Right',
  'Izquierda': 'Left',
  'elegir imagen': 'choose image',
  '{}: elegir imagen': '{}: choose image',
  'clic para elegir una imagen, o varias para llenar esta versión hacia abajo': 'click to choose one image, or several to fill this version downwards',
  'subir': 'move up',
  'bajar': 'move down',
  'quitar': 'remove',
  'quitar {}': 'remove {}',
  'Intercambiar izquierda y derecha': 'Swap left and right',
  'Completa el par vacío antes de compartir.': 'Fill the empty pair before sharing.',
  'Completa los huecos antes de compartir.': 'Fill the gaps before sharing.',
  'Puedes guardar el proyecto para seguir después.': 'You can save the project and continue later.',
  'Las imágenes tienen tamaños distintos ({}) · el diff y los recortes 1:1 necesitan dimensiones idénticas.': 'The images have different sizes ({}) · the diff and the 1:1 crops need identical dimensions.',
  '1 par listo': '1 pair ready',
  '{} pares listos': '{} pairs ready',
  '1 cuadro listo · {} versiones en cada uno': '1 frame ready · {} versions in it',
  '{} cuadros listos · {} versiones en cada uno': '{} frames ready · {} versions in each',
  '· y exporta cuando quieras:': '· export whenever you like:',
  '1 imagen con pérdida': '1 lossy image',
  '{} imágenes con pérdida': '{} lossy images',
  '(JPEG o WebP con pérdida): la evidencia se degrada y el S2 medirá esa compresión extra, no tu encode. Se aceptan, pero usa PNG sin pérdida para comparaciones serias.': '(JPEG or lossy WebP): the evidence is degraded and S2 will measure that extra compression, not your encode. They are accepted, but use lossless PNG for serious comparisons.',
  // Video
  'De videos a comparación': 'From videos to a comparison',
  'Suelta el máster y los encodes. Marcas momentos en la línea de tiempo y la herramienta hace una captura en el instante pedido de cada video. Revisa que las capturas correspondan al mismo momento.': 'Drop the master and the encodes. You mark moments on the timeline and the tool takes a screenshot of each video at that instant. Check that the screenshots show the same moment.',
  'Elegir videos': 'Choose videos',
  'Suelta los videos aquí': 'Drop the videos here',
  'MP4 / WebM / MOV que tu navegador sepa abrir · el máster y cada encode': 'MP4 / WebM / MOV that your browser can open · the master and each encode',
  '← anterior': '← previous',
  'siguiente →': 'next →',
  'Marcar aquí': 'Mark here',
  'capturas en PNG sin pérdida': 'screenshots as lossless PNG',
  'Capturar todo': 'Capture all',
  'Resultado por marca y variante': 'Result per mark and variant',
  'La captura depende del decodificador y de la conversión de color del navegador. Para evaluar HDR o sincronía exacta entre frames, usa capturas de tu propio proceso de extracción.': 'The screenshot depends on the browser\'s decoder and color conversion. To judge HDR or exact frame alignment, use screenshots from your own extraction process.',
  'máster': 'master',
  'Máster': 'Master',
  'variante {}': 'variant {}',
  'este navegador no puede abrir este archivo (¿códec o contenedor?) · pruébalo en otro navegador o usa capturas': 'this browser cannot open this file (codec or container?) · try another browser or use screenshots',
  'sin marcas · reproduce, pausa donde quieras comparar, y marca': 'no marks · play, pause where you want to compare, and mark',
  'clic para saltar ahí': 'click to jump there',
  'El video no tiene una imagen decodificada.': 'The video has no decoded image.',
  'Error al decodificar el video.': 'Error decoding the video.',
  'Se agotó el tiempo para buscar la captura.': 'Timed out while seeking to the screenshot.',
  'El tiempo marcado queda fuera de este video.': 'The marked time is outside this video.',
  'primero suelta los videos': 'drop the videos first',
  'primero marca al menos un momento': 'mark at least one moment first',
  'Marca {} · {} s · {} ({}): ': 'Mark {} · {} s · {} ({}): ',
  'pendiente': 'pending',
  'Abriendo {}…': 'Opening {}…',
  'Se agotó el tiempo al abrir el video.': 'Timed out while opening the video.',
  'desconocido': 'unknown',
  'El navegador no pudo abrir o decodificar este archivo (código {}).': 'The browser could not open or decode this file (code {}).',
  'buscando el instante pedido…': 'seeking to the requested instant…',
  'El navegador no pudo generar la imagen.': 'The browser could not create the image.',
  'captura lista': 'screenshot ready',
  'Se conservó la captura anterior.': 'The previous screenshot was kept.',
  'Falló: {}': 'Failed: {}',
  'Capturas procesadas: {}/{}. Fallas: {}.': 'Screenshots processed: {}/{}. Failures: {}.',
  '{}/{} capturas listas. Revisa las {} fallas indicadas abajo.': '{}/{} screenshots ready. Check the {} failures listed below.',
  '✓ {} capturas listas': '✓ {} screenshots ready',
  'Seguir en Avanzado → revisar imágenes': 'Continue in Advanced → check images',
  // Avanzado
  'Proyecto': 'Project',
  'El título ayuda a identificar la comparación. Puedes dejarlo vacío.': 'The title helps identify the comparison. You can leave it empty.',
  'Título': 'Title',
  'p. ej. Comparación de encodes': 'e.g. Encode comparison',
  'Sin título, la página se llamará «Comparación».': 'Without a title, the page will be called "Comparison".',
  'Opciones para hosting estático': 'Options for static hosting',
  'Versión del archivo': 'File version',
  'Variantes': 'Variants',
  'Cada variante es una versión de la imagen, como la fuente o un encode. La primera es la referencia para S2. Codec, CRF, bitrate y comandos son opcionales.': 'Each variant is one version of the image, such as the source or an encode. The first one is the reference for S2. Codec, CRF, bitrate and commands are optional.',
  '+ Agregar variante': '+ Add variant',
  'Un frame es un momento que quieres comparar. El identificador debe coincidir con el nombre de archivo (variante_1001.png). La etiqueta opcional describe la escena.':
    'A frame is a moment you want to compare. Its identifier must match the file name (<span class="mono">variant_1001.png</span>). The optional label describes the scene.',
  '+ Agregar frame': '+ Add frame',
  'Imágenes': 'Images',
  'Revisar': 'Review',
  'Llena la tabla. Suelta archivos llamados <variante>_<frame>.png y caen solos en su casilla. O llena una variante entera: clic en su nombre en la tabla (o suelta ahí sus imágenes) y van a sus frames en orden de nombre.':
    'Fill the table. Drop files named <span class="mono">&lt;variant&gt;_&lt;frame&gt;.png</span> and they land in their cell. Or fill a whole variant: click its name in the table (or drop its images there) and they go to its frames in name order.',
  'Elegir imágenes para la tabla': 'Choose images for the table',
  'Agrega varias imágenes por nombre': 'Add several images by name',
  'se emparejan por id de variante, nombre de variante o número/etiqueta del frame': 'matched by variant id, variant name, or frame number/label',
  'lo que no exista (variante o frame) se crea solo del nombre del archivo': 'whatever does not exist yet (variant or frame) is created from the file name',
  'izquierda por defecto': 'left by default',
  'derecha por defecto': 'right by default',
  'clic para cambiar el color': 'click to change the color',
  'nombre (p. ej. Fuente, CRF 26)': 'name (e.g. Source, CRF 26)',
  'codec · p. ej. AV1, x264, HEVC': 'codec · e.g. AV1, x264, HEVC',
  'número de calidad': 'quality number',
  'nota extra · sale bajo el botón': 'extra note · shown under the button',
  'comando del encoder (tooltip)': 'encoder command (tooltip)',
  'Métrica opcional: VMAF 96.2': 'Optional metric: VMAF 96.2',
  'Se muestra bajo el nombre de la variante': 'Shown under the variant name',
  'Nombre': 'Name',
  'Bitrate en Mb/s': 'Bitrate in Mb/s',
  'Nota': 'Note',
  'Comando del encoder': 'Encoder command',
  'Métrica opcional': 'Optional metric',
  '{} de la variante {}': '{} of variant {}',
  'Hacen falta al menos dos variantes para comparar.': 'You need at least two variants to compare.',
  'número del frame · se usa en los nombres de archivo': 'frame number · used in the file names',
  'etiqueta (opcional · p. ej. escena oscura, primer plano de grano)': 'label (optional · e.g. dark scene, grain close-up)',
  'Usa un identificador único de frame, con letras, números o guiones.': 'Use a unique frame identifier, with letters, numbers or hyphens.',
  'Hace falta al menos un frame.': 'You need at least one frame.',
  '1 variante nueva ({})': '1 new variant ({})',
  '{} variantes nuevas ({})': '{} new variants ({})',
  '1 frame nuevo': '1 new frame',
  '{} frames nuevos': '{} new frames',
  '{} sin asignar': '{} unassigned',
  '✓ todo asignado': '✓ everything assigned',
  'nombre ambiguo · usa el nombre completo o el identificador de la variante': 'ambiguous name · use the variant\'s full name or its identifier',
  'no se pudo interpretar el nombre · se espera <variante>_<frame>': 'could not read the name · expected <variant>_<frame>',
  'nombre sin guion bajo · se espera <variante>_<frame>': 'name without an underscore · expected <variant>_<frame>',
  'Primero define variantes y frames.': 'Define variants and frames first.',
  'Clic (o suelta aquí) para elegir todas las imágenes de esta variante: llenan sus frames en orden de nombre': 'Click (or drop here) to choose all the images of this variant: they fill its frames in name order',
  'elegir todas': 'choose all',
  'suelta / clic': 'drop / click',
  'Archivos sin asignar': 'Unassigned files',
  'variante…': 'variant…',
  'descartar este archivo': 'discard this file',
  // revisar y compartir
  'Revisar y compartir': 'Review and share',
  'Completa las imágenes que falten y abre la vista previa antes de compartir.': 'Add any missing images and open the preview before sharing.',
  'Calcular S2 (SSIMULACRA2)': 'Compute S2 (SSIMULACRA2)',
  'puntúa cada frame de cada variante contra la primera (la referencia). Sale en la página bajo el nombre de cada variante. Tarda unos segundos por imagen · se calcula localmente, como todo lo demás.': 'scores every frame of every variant against the first one (the reference). It shows on the page under each variant\'s name. Takes a few seconds per image · computed locally, like everything else.',
  'la página exacta que van a ver quienes abran tu export.': 'the exact page people will see when they open your export.',
  'Abrir vista previa': 'Open preview',
  'HTML de un solo archivo': 'Single-file HTML',
  'motor + imágenes embebidos. Se abre con doble clic, sin internet.': 'engine + images embedded. Opens with a double click, offline.',
  'Descargar .html': 'Download .html',
  'Carpeta autocontenida (.zip)': 'Self-contained folder (.zip)',
  'index.html + compare.js + manifest.json + img/ · lista para cualquier hosting estático.': 'index.html + compare.js + manifest.json + img/ · ready for any static hosting.',
  'Descargar .zip': 'Download .zip',
  'Paquete .cmp': '.cmp package',
  'el formato de gatos.pics · para guardar o subir por tu cuenta.': 'the gatos.pics format · to keep or upload yourself.',
  'Descargar .cmp': 'Download .cmp',
  'Publicar en gatos.pics': 'Publish on gatos.pics',
  'sube la página tal cual y te da el link para compartir. Se puede borrar con la llave que entrega.': 'uploads the page as it is and gives you the link to share. It can be deleted with the key you receive.',
  'Publicar y obtener link': 'Publish and get the link',
  'Actualizar una página publicada': 'Update a published page',
  'reemplaza el contenido de una página que ya publicaste y conserva su mismo enlace. Usa su llave de borrado o tu llave API.': 'replaces the content of a page you already published and keeps its link. Uses its delete key or your API key.',
  'Actualizar una página ya publicada': 'Update a page already published',
  '← Anterior': '← Back',
  'Siguiente →': 'Next →',
  '1 casilla vacía · ahí la página mostrará un cuadro roto.': '1 empty cell · the page will show a broken frame there.',
  '{} casillas vacías · ahí la página mostrará un cuadro roto.': '{} empty cells · the page will show a broken frame there.',
  'Las {} casillas llenas.': 'All {} cells filled.',
  'Hacen falta al menos dos variantes.': 'You need at least two variants.',
  'Hay identificadores de frame repetidos. Usa uno distinto para cada momento.': 'Some frame identifiers are repeated. Use a different one for each moment.',
  'Los identificadores de frame admiten letras, números, guion y guion bajo (máximo 32).': 'Frame identifiers take letters, numbers, hyphen and underscore (32 at most).',
  'Tamaños de imagen mezclados ({}) · el diff y los recortes 1:1 necesitan dimensiones idénticas.': 'Mixed image sizes ({}) · the diff and the 1:1 crops need identical dimensions.',
  'Tamaño del paquete ≈ {} MB en base64.': 'Package size ≈ {} MB in base64.',
  'Pesado · considera menos frames o imágenes más chicas.': 'Heavy · consider fewer frames or smaller images.',
  '1 archivo sin asignar NO va a entrar a la página.': '1 unassigned file will NOT go into the page.',
  '{} archivos sin asignar NO van a entrar a la página.': '{} unassigned files will NOT go into the page.',
  'Agrega dos imágenes a cada par antes de compartir.': 'Add two images to every pair before sharing.',
  'Completa todas las versiones de cada cuadro antes de compartir.': 'Fill every version of every frame before sharing.',
  '«{}» pesa {} MB: el límite por imagen es 25 MiB.': '"{}" weighs {} MB: the limit per image is 25 MiB.',
  'Las imágenes suman {} MiB: el límite por página es 1 GiB. Reduce frames o variantes.': 'The images add up to {} MiB: the limit per page is 1 GiB. Use fewer frames or variants.',
  'Comparación': 'Comparison',
  'Preparación cancelada.': 'Preparation cancelled.',
  // vista previa, guardar, abrir
  'La captura de video está en curso; espera a que termine para abrir la vista previa.': 'Video capture is running; wait for it to finish before opening the preview.',
  'La captura de video está en curso; espera a que termine para guardar.': 'Video capture is running; wait for it to finish before saving.',
  'La captura de video está en curso; espera a que termine para importar.': 'Video capture is running; wait for it to finish before importing.',
  'La captura de video está en curso; espera a que termine para actualizar.': 'Video capture is running; wait for it to finish before updating.',
  'La captura de video está en curso; espera a que termine para publicar.': 'Video capture is running; wait for it to finish before publishing.',
  'Generando vista previa…': 'Building the preview…',
  'El shell del visor no tiene las etiquetas esperadas.': 'The viewer shell is missing the expected tags.',
  'Este navegador no puede armar la vista previa ni exportar: actualízalo.': 'This browser cannot build the preview or export: please update it.',
  'Abrir este archivo reemplaza el proyecto que tienes abierto. ¿Continuar?': 'Opening this file replaces the project you have open. Continue?',
  'No se importó nada: tu proyecto sigue como estaba.': 'Nothing was imported: your project is unchanged.',
  'No es un paquete {}.': 'This is not a {} package.',
  'Faltan los datos del proyecto.': 'The project data is missing.',
  'identificador de variante o frame no válido: se admite A-Z a-z 0-9 _ y -, máximo 32.': 'invalid variant or frame identifier: A-Z a-z 0-9 _ and - are allowed, 32 at most.',
  'No se pudo leer este paquete: {}': 'Could not read this package: {}',
  'Volver al creador': 'Back to the creator',
  'esta es exactamente la página exportada · mismo motor, imágenes embebidas': 'this is exactly the exported page · same engine, embedded images',
  'vista previa': 'preview',
  'Demasiadas entradas para un zip ({}): el formato admite 65535.': 'Too many entries for a zip ({}): the format takes 65535.',
  '«{}» no cabe en un zip: el límite por entrada son 4 GiB.': '"{}" does not fit in a zip: the limit per entry is 4 GiB.',
  'El zip proyectado pasa de 4 GiB ({}): el formato sin ZIP64 no lo admite. Exporta menos imágenes o más chicas.': 'The zip would exceed 4 GiB ({}): the format without ZIP64 cannot hold it. Export fewer or smaller images.',
  // pie
  'Todo se prepara en tu navegador. Publicar sube las imágenes y los datos a gatos.pics.': 'Everything is prepared in your browser. Publishing uploads the images and data to gatos.pics.',
  'suelta un archivo .cmp en cualquier parte de la ventana para importarlo · con un proyecto abierto, te pedimos confirmación': 'drop a .cmp file anywhere in the window to import it · with a project open, we ask you to confirm',
  // publicar
  'El frame {} pesa {} MiB entre todas sus variantes: el límite por frame es 280 MiB.': 'Frame {} weighs {} MiB across all its variants: the limit per frame is 280 MiB.',
  'Esta página pesa demasiado para un solo envío y tiene variantes parciales: reduce frames o imágenes.': 'This page is too heavy for a single upload and has partial variants: use fewer frames or images.',
  'El servidor pudo recibir esta parte. Reintentar la vuelve a mandar; no crea otra página.': 'The server may have received this part. Retrying sends it again; it does not create another page.',
  'Parte {} de {}': 'Part {} of {}',
  ' (la página ya existe, incompleta: {})': ' (the page already exists, incomplete: {})',
  'el visor no cargó': 'the viewer did not load',
  'Espera a que el visor se acomode.': 'Wait for the viewer to settle.',
  'imagen fuera de tamaño': 'image out of size',
  'El servidor pudo recibir el paquete. Reintentar puede crear otra página.': 'The server may have received the package. Retrying may create another page.',
  'El servidor pudo recibir el paquete. Reintentar vuelve a reemplazar la misma página, sin cambiar su enlace.': 'The server may have received the package. Retrying replaces the same page again, keeping its link.',
  'Página actualizada. El enlace sigue siendo el mismo: {} (si no ves el cambio, recarga la página).': 'Page updated. The link is still the same: {} (if you do not see the change, reload the page).',
  'Creando la imagen para compartir…': 'Creating the share image…',
  'Imagen para compartir lista: los códigos de abajo ya la usan.': 'Share image ready: the codes below already use it.',
  'No se pudo crear la imagen para compartir: los códigos usan la primera imagen. Puedes crearla desde la página, con «Compartir».': 'Could not create the share image: the codes use the first image. You can create it from the page, with "Share".',
  'Publicar sin límite necesita tu llave API. Pégala aquí (el creador la recuerda para la próxima):': 'Publishing without a limit needs your API key. Paste it here (the creator remembers it for next time):',
  'Esa llave no sirvió para esta página. Pega la llave de borrado de la página o tu llave API:': 'That key did not work for this page. Paste the page\'s delete key or your API key:',
  'Enlace de la página que quieres actualizar (el enlace no cambia):': 'Link of the page you want to update (the link does not change):',
  'Ese enlace no es de una página de gatos.pics (debe contener /p/ y su código).': 'That link is not a gatos.pics page (it must contain /p/ and its code).',
  'Pega la llave de borrado de esa página (o tu llave API):': 'Paste that page\'s delete key (or your API key):',
  'Esto reemplaza TODO el contenido de esa página con el proyecto abierto. El enlace y la llave siguen igual. ¿Continuar?': 'This replaces ALL the content of that page with the open project. The link and the key stay the same. Continue?',
  'Publicado': 'Published',
  'Guarda la llave: sirve para borrar la página, actualizar su imagen compartida y reemplazar su contenido sin cambiar el enlace. Cualquiera con el enlace puede ver la comparación.': 'Keep the key: it lets you delete the page, update its share image and replace its content without changing the link. Anyone with the link can see the comparison.',
  'Link para compartir': 'Link to share',
  'Copiar': 'Copy',
  'Llave de borrado': 'Delete key',
  'Para foros (BBCode, con vista previa clicable)': 'For forums (BBCode, with a clickable preview)',
  'Borrar más tarde': 'Delete later',
  'Abrir la página': 'Open the page',
  'Guardar enlace y llave': 'Save link and key',
  'Cerrar': 'Close',
  // ayuda, guías y comentarios
  '¿Qué quieres hacer?': 'What do you want to do?',
  'Elige tu caso y te lo mostramos paso a paso sobre la pantalla, con capturas de ejemplo.': 'Pick your case and we show it step by step on the screen, with sample screenshots.',
  'Enviar comentarios': 'Send feedback',
  '¿Algo no funciona, falta o se puede mejorar? Cuéntanos. No pedimos ningún dato; si quieres respuesta, deja tu usuario de Discord en el mensaje.': 'Is something broken, missing, or could be better? Tell us. We ask for no personal data; if you want a reply, leave your Discord username in the message.',
  'Escribe aquí…': 'Write here…',
  'Tu comentario': 'Your feedback',
  'Enviar comentario': 'Send feedback',
  'Ver la bienvenida': 'Show the welcome screen',
  'Guía': 'Guide',
  'Atrás': 'Back',
  'Siguiente': 'Next',
  'Terminar': 'Finish',
  'Salir de la guía': 'Leave the guide',
  '{} · paso {} de {}': '{} · step {} of {}',
  '{} · ejemplo': '{} · sample',
  '(Estas capturas son de ejemplo.)': '(These screenshots are samples.)',
  'Escribe tu comentario primero.': 'Write your feedback first.',
  'Enviando…': 'Sending…',
  'Ya enviaste varios hace poco. Prueba más tarde.': 'You sent several a moment ago. Try again later.',
  'Enviado. Gracias: lo leemos todo.': 'Sent. Thank you: we read everything.',
  'No se pudo enviar: sin conexión con gatos.pics.': 'Could not send: no connection to gatos.pics.',
  'Tengo una carpeta por versión': 'I have one folder per version',
  'Cada versión (fuente, encode…) con sus capturas aparte. Los nombres de archivo no importan.': 'Each version (source, encode…) has its screenshots apart. File names do not matter.',
  'Empieza en Básico: no hay nada que configurar.': 'Start in Basic: there is nothing to set up.',
  'Cada versión tiene un nombre. Escribe el tuyo: Fuente, Encode, WEB-DL…': 'Each version has a name. Type yours: Source, Encode, WEB-DL…',
  'Pulsa «Elegir sus imágenes» y selecciona TODAS las capturas de esta versión de una vez. También puedes soltarlas sobre el nombre.': 'Press "Choose its images" and select ALL the screenshots of this version at once. You can also drop them on the name.',
  'Quedan en fila, una por cuadro, en orden de nombre.': 'They line up, one per frame, in name order.',
  'Ahora la segunda versión, igual. No importa que sus archivos se llamen igual que los de la primera.': 'Now the second version, the same way. It does not matter if its files have the same names as the first one\'s.',
  'Cada fila es un cuadro con sus versiones lado a lado. Si a una versión le faltan capturas, el hueco queda a la vista.': 'Each row is a frame with its versions side by side. If a version is missing screenshots, the gap stays visible.',
  '¿Tres o más versiones? Agrega otra y llénala del mismo modo.': 'Three or more versions? Add another one and fill it the same way.',
  'Vista previa: revisa la comparación antes de compartirla.': 'Preview: check the comparison before you share it.',
  'Publicar te da el enlace y el código para foros. La imagen para compartir se crea sola.': 'Publish gives you the link and the code for forums. The share image is created automatically.',
  'Tengo todas las capturas juntas': 'I have all the screenshots together',
  'Una sola carpeta, con nombres que dicen la versión y el cuadro.': 'A single folder, with names that say the version and the frame.',
  'Suelta aquí todas las capturas juntas, o haz clic para elegirlas. Si el nombre dice la versión y el cuadro (fuente_01, Encode - 01, 01_encode) se agrupan solas. Si no lo dice, usa la guía «una carpeta por versión».': 'Drop all the screenshots here together, or click to choose them. If the name says the version and the frame (source_01, Encode - 01, 01_encode) they group themselves. If it does not, use the "one folder per version" guide.',
  'Cada fila es un cuadro con todas sus versiones. La referencia (fuente, src, máster) queda a la izquierda.': 'Each row is a frame with all its versions. The reference (source, src, master) goes on the left.',
  'Los nombres de las versiones salen de los archivos. Corrígelos aquí si hace falta.': 'The version names come from the files. Fix them here if needed.',
  'fuente': 'source',
});
I18N.apply();
I18N.wire();
